import { Navigation } from "@/components/navigation/Navigation";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useFirebaseAuth } from "@/hooks/use-firebase-auth";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { ArrowRight, LogOut, Settings, UserRound } from "lucide-react";

export default function Profile() {
  const navigate = useNavigate();
  const { user: firebaseUser, loading: firebaseLoading, logout: firebaseLogout } = useFirebaseAuth();
  const getInitials = () => firebaseUser?.displayName ? firebaseUser.displayName.split(" ").map((part) => part[0]).join("").toUpperCase().slice(0, 2) : firebaseUser?.email?.[0].toUpperCase() || "U";
  if (firebaseLoading) return <div className="page-shell grid min-h-screen place-items-center"><span className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" /></div>;
  return <div className="page-shell"><Navigation /><main className="content-container pt-28"><div className="mx-auto max-w-2xl"><p className="section-eyebrow">Личное пространство</p><h1 className="section-heading">Профиль</h1>{firebaseUser ? <Card className="mt-7 border-white/[0.10]"><CardHeader className="border-b border-white/[0.08] p-6"><div className="flex items-center gap-4"><Avatar className="h-16 w-16 border border-primary/30"><AvatarImage src={firebaseUser.photoURL || undefined} alt={firebaseUser.displayName || firebaseUser.email || "Пользователь"} /><AvatarFallback className="bg-primary/15 text-lg font-extrabold text-primary">{getInitials()}</AvatarFallback></Avatar><div><CardTitle className="text-xl">{firebaseUser.displayName || "Пользователь"}</CardTitle><CardDescription className="mt-1">{firebaseUser.email}</CardDescription></div></div></CardHeader><CardContent className="space-y-6 p-6"><div><h2 className="font-extrabold">Ваш аккаунт</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Настройте внешний вид сервиса, а фильмы и история останутся доступны через меню профиля.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Button variant="outline" onClick={() => navigate("/settings")} className="flex-1"><Settings className="h-4 w-4" />Настройки</Button><Button variant="outline" onClick={firebaseLogout} className="flex-1 border-destructive/30 text-destructive hover:border-destructive/60 hover:bg-destructive/10 hover:text-destructive"><LogOut className="h-4 w-4" />Выйти</Button></div></CardContent></Card> : <Card className="mt-7 border-white/[0.10]"><CardContent className="p-8 text-center"><UserRound className="mx-auto h-9 w-9 text-primary" /><h2 className="mt-4 text-xl font-extrabold">Войдите в свой профиль</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Сохраняйте фильмы, возвращайтесь к истории и настраивайте сервис под себя.</p><Button onClick={() => navigate("/auth")} className="mt-6"><ArrowRight className="h-4 w-4" />Войти или зарегистрироваться</Button></CardContent></Card>}</div></main></div>;
}
